name: eddl
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - cmake
  - eigen
  - zlib
  - cudatoolkit
  - graphviz  # Build & Run
  - wget
  - doxygen  # Docs
  - python
  - pip
  - pip:
    - sphinx
    - breathe
    - sphinx_rtd_theme
    - sphinx-tabs