name: eddl
channels:
  - conda-forge
  - defaults
dependencies:
  - git
  - graphviz
  - wget
  - gcc
  - cmake
  - openmp
  - blas
  - eigen
  - cudatoolkit
  - zlib
  - gtest
  - benchmark
  - protobuf
  - libprotobuf
