name: eddl
channels:
  - conda-forge
  - defaults
  - anaconda
  - philbrik
dependencies:
  - graphviz  # Build & Run
  - wget
  - cmake
  - eigen
  - cudatoolkit
  - zlib
  - gtest
  - boost
  - protobuf  # Protobuf
  - libprotobuf
  - doxygen  # Docs
  - python
  - pip
  - pip:
    - sphinx
    - breathe
    - sphinx_rtd_theme
    - sphinx-tabs