{% set name = "eddl-gpu" %}  # If this is a package for GPU, use: "eddl-gpu"
{% set version = "v0.5.3a" %}
{% set sha256 = "e92e0fe9a36d0869e5608005d38e2f389cc0d9ea8127e69de751662c2429d730" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/eddl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cmake
    - eigen
    - zlib
    - protobuf
    - cudatoolkit
    - graphviz
    - wget
  run:
    - cmake
    - eigen
    - zlib
    - protobuf
    - cudatoolkit
    - graphviz
    - wget

test:
  commands:
    - test -d ${PREFIX}/include/eddl  # [unix]
    - test -f ${PREFIX}/include/eddl/apis/eddl.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/eddl/EDDLConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/libeddl${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/deephealthproject/eddl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'EDDL is an optimized tensor library for distributed deep learning with hardware transparency support for CPUs, GPUs and FPGAs'
  doc_url: https://deephealthproject.github.io/eddl/
  dev_url: https://github.com/deephealthproject/eddl/
