{% set name = "eddl-cpu" %}  # If this is a package for GPU, use: "eddl-gpu"
{% set version = "0.4.3" %}
{% set sha256 = "07492ae01d13a8b9c686ea5578dfc8740be751dc9b82d61ef669699054b9dd7f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/eddl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    #- llvm-openmp  # IMPORTANT!!! JUST FOR MAC OS. NOT COMPATIBLE WITH OTHER BUILDS. DISABLE IF NOT NEEDED
  host:
    - graphviz
    - wget
    - eigen
    - zlib
    - gtest
    - protobuf
    - libprotobuf
    - blas  # From here and on, these are extra dependencies that might not be used
    - cudatoolkit
    - mkl >=2019  
    - mkl-include
  run:
    - graphviz
    - wget
    - eigen
    - zlib
    - gtest
    - protobuf
    - libprotobuf
    - blas  # From here and on, these are extra dependencies that might not be used
    - cudatoolkit
    - mkl >=2019  
    - mkl-include

test:
  commands:
    - test -d ${PREFIX}/include/eddl  # [unix]
    - test -f ${PREFIX}/include/eddl/tensor/tensor.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/eddl/eddlConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\tensor\tensor.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\eddlConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/deephealthproject/eddl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'EDDL is an optimized tensor library for distributed deep learning with hardware transparency support for CPUs, GPUs and FPGAs'
  doc_url: https://deephealthproject.github.io/eddldocs/
  dev_url: https://github.com/deephealthproject/eddl
