name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install utilities
        run: sudo apt-get install -y cmake wget graphviz zlib1g-dev
      - name: Install Eigen3
        run: sudo apt-get install -y libeigen3-dev
      - name: Install gTests
        run: sudo apt-get install -y libgtest-dev
      - name: Compile
        run: |
          mkdir build
          cd build
          cmake ..
          make
          make test
