name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install utilities
        run: sudo apt-get install -y cmake git wget graphviz zlib1g-dev libboost-all-dev
      - name: Install Eigen3
        run: sudo apt-get install -y libeigen3-dev
      - name: Install gTests
        run: |
          sudo apt-get install -y libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
      - name: Compile
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TARGET=CPU -BUILD_OPENMP=ON -BUILD_PROTOBUF=OFF -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON
          make
          make test ARGS=-V
