name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install utilities
        run: sudo apt-get install -y cmake git wget graphviz
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Test
        run: |
          cd build
          ctest --verbose
